on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Build and deploy to Docker Hub

jobs:
  deploy:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install docker
      run: |
        brew install --cask docker
        /Applications/Docker.app/Contents/MacOS/install

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        platforms: linux/arm/v7
        push: true
        tags: c4stus/raspberrypi:mqttbroker
